version: '3.0'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass123!
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped

volumes:
  postgres:

